name: Release

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  build-frontend:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./front/
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm version ${{ env.VERSION }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build-prod
      - uses: actions/upload-artifact@v4
        with:
          name: static
          path: ./static

  build-images:
    needs: build-frontend
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    outputs:
      image: ${{ steps.image.outputs.ref }}
      digest: ${{ steps.build.outputs.digest }}
      hashes: ${{ steps.hashes.outputs.subjects }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/download-artifact@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: release image reference
        id: image
        run: echo "ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}" >> "$GITHUB_OUTPUT"

      - uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}

      - name: extract amd64 binary from the image
        run: |
          docker create --platform linux/amd64 --name amd64 ${{ steps.image.outputs.ref }} &&
          docker cp amd64:/usr/bin/coroot /tmp/coroot-amd64

      - name: extract arm64 binary from the image
        run: |
          docker create --platform linux/arm64 --name arm64 ${{ steps.image.outputs.ref }} &&
          docker cp arm64:/usr/bin/coroot /tmp/coroot-arm64

      - name: hash release binaries for SLSA3 provenance
        id: hashes
        run: echo "subjects=$(sha256sum /tmp/coroot-amd64 /tmp/coroot-arm64 | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: upload amd64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/coroot-amd64
          asset_name: coroot-amd64
          asset_content_type: application/octet-stream

      - name: upload arm64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/coroot-arm64
          asset_name: coroot-arm64
          asset_content_type: application/octet-stream

      - uses: actions/github-script@v7
        env:
          RELEASE_ID: ${{ github.event.release.id }}
        with:
          script: |
            const { RELEASE_ID } = process.env
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: `${RELEASE_ID}`,
              prerelease: false,
              make_latest: true
            })

  provenance-binaries:
    needs: build-images
    permissions:
      actions: read
      contents: write
      id-token: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: ${{ needs.build-images.outputs.hashes }}
      upload-assets: true

  provenance-image:
    needs: build-images
    permissions:
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.build-images.outputs.image }}
      digest: ${{ needs.build-images.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
